// Maps the SUI icon names used in dvz-ui to Lucide component names.
// Consumers import the Icon wrapper component — not this type directly.
export type SuiIconName =
  | 'search'
  | 'arrow alternate circle left outline'
  | 'close'
  | 'times'
  | 'world'
  | 'envelope'
  | 'angle down'
  | 'chevron down'
  | 'angle up'
  | 'chevron up'
  | 'angle left'
  | 'angle right'
  | 'angle double left'
  | 'angle double right'
  | 'plus'
  | 'minus'
  | 'expand'
  | 'expand arrows alternate'
  | 'download'
  | 'filter'
  | 'info circle'
  | 'check'
  | 'warning'
  | 'warning circle'
  | 'times circle'
  | 'check circle'
  | 'spinner'
  | 'bars'
  | 'list'
  | 'home'
  | 'external link'
  | 'external link alternate'
  | 'map marker'
  | 'map marker alternate'
  | 'chart bar'
  | 'chart line'
  | 'chart pie'
  | 'table'
  | 'edit'
  | 'trash'
  | 'copy'
  | 'share'
  | 'link'
  | 'lock'
  | 'unlock'
  | 'user'
  | 'users'
  | 'cog'
  | 'settings'
  | 'bell'
  | 'calendar'
  | 'clock'
  | 'eye'
  | 'eye slash'
  | 'upload'
  | 'file'
  | 'file pdf'
  | 'print'
  | 'refresh'
  | 'redo'
  | 'undo'
  | 'sort'
  | 'sort ascending'
  | 'sort descending';
