import type { Config } from 'tailwindcss';

// Re-use the same config from @devgateway/ui so classes match
const config: Config = {
  content: [
    './src/**/*.{ts,tsx,js,jsx}',
    '../ui/src/**/*.{ts,tsx}',
    '../react-lib/wp-react-lib/src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sui: ['Lato', "'Helvetica Neue'", 'Arial', 'Helvetica', 'sans-serif'],
      },
      colors: {
        'sui-blue':          '#2185d0',
        'sui-blue-hover':    '#1678c2',
        'sui-blue-focus':    '#0d71bb',
        'sui-blue-active':   '#1a69a4',
        'sui-green':         '#21ba45',
        'sui-green-hover':   '#16ab39',
        'sui-green-active':  '#198f35',
        'sui-red':           '#db2828',
        'sui-red-hover':     '#d01919',
        'sui-red-active':    '#b21e1e',
        'sui-orange':        '#f2711c',
        'sui-orange-hover':  '#f26202',
        'sui-yellow':        '#fbbd08',
        'sui-yellow-hover':  '#eaae00',
        'sui-teal':          '#00b5ad',
        'sui-teal-hover':    '#009c95',
        'sui-violet':        '#6435c9',
        'sui-violet-hover':  '#5829bb',
        'sui-purple':        '#a333c8',
        'sui-purple-hover':  '#9627ba',
        'sui-pink':          '#e03997',
        'sui-pink-hover':    '#e61a8d',
        'sui-brown':         '#a5673f',
        'sui-brown-hover':   '#975b33',
        'sui-grey':          '#767676',
        'sui-grey-hover':    '#838383',
        'sui-black':         '#1b1c1d',
        // Button palette
        'sui-btn':           '#e0e1e2',
        'sui-btn-hover':     '#cacbcd',
        'sui-btn-active':    '#babbbc',
        'sui-btn-secondary': '#1b1c1d',
        'sui-btn-secondary-hover': '#27292a',
        // Text
        'sui-text':     'rgba(0,0,0,.87)',
        'sui-subtext':  'rgba(0,0,0,.6)',
        // Borders / surfaces
        'sui-border':        'rgba(34,36,38,.15)',
        'sui-border-hover':  'rgba(34,36,38,.3)',
        'sui-checkbox-border': '#d4d4d5',
        'sui-focus-border':  '#85b7d9',
        'sui-checkbox-focus':'#96c8da',
        'sui-placeholder':   'rgba(191,191,191,.87)',
        // Semantic states
        'sui-error-bg':      '#fff6f6',
        'sui-error-border':  '#e0b4b4',
        'sui-error-text':    '#9f3a38',
        'sui-error-header':  '#912d2b',
        'sui-warning-bg':    '#fffaf3',
        'sui-warning-border':'#c9ba9b',
        'sui-warning-text':  '#573a08',
        'sui-warning-header':'#794b02',
        'sui-info-bg':       '#f8ffff',
        'sui-info-border':   '#a9d5de',
        'sui-info-text':     '#0e566c',
        'sui-info-header':   '#0e566c',
        'sui-success-bg':    '#fcfff5',
        'sui-success-border':'#a3c293',
        'sui-success-text':  '#2c662d',
        'sui-success-header':'#1a531b',
      },
      borderRadius: {
        'sui':    '.28571429rem',
        'sui-sm': '.21428571rem',
      },
      boxShadow: {
        'segment':       '0 1px 2px 0 rgba(34,36,38,.15)',
        'segment-hover': '0 2px 4px 0 rgba(34,36,38,.12), 0 2px 10px 0 rgba(34,36,38,.08)',
        'sui-btn':       '0 0 0 1px transparent inset, 0 0 0 0 rgba(34,36,38,.15) inset',
        'sui-modal':     '1px 3px 3px 0 rgba(0,0,0,.2), 1px 3px 15px 2px rgba(0,0,0,.2)',
        'sui-dropdown':  '0 2px 3px 0 rgba(34,36,38,.15)',
        'sui-msg-info':  'inset 0 0 0 1px #a9d5de, inset 0 0 0 0 transparent',
        'sui-msg-warn':  'inset 0 0 0 1px #c9ba9b, inset 0 0 0 0 transparent',
        'sui-msg-pos':   'inset 0 0 0 1px #a3c293, inset 0 0 0 0 transparent',
        'sui-msg-neg':   'inset 0 0 0 1px #e0b4b4, inset 0 0 0 0 transparent',
      },
    },
  },
  plugins: [],
};

export default config;
